version: '3.0'

services:
  docker:
    container_name: mysql-schedule
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: docker-mysql-schedule
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:

